version: "3.7"
services:
  router1:
    privileged: true
    container_name: r1
    build: ./r1
    networks:
       r1_r2:
        ipv4_address: "172.19.0.11"
    expose:
       - "179"
  router2:
    privileged: true
    container_name: r2
    build: ./r2
    networks:
       r1_r2:
        ipv4_address: "172.19.0.12"       
       r666_r2:
        ipv4_address: "182.19.0.12"
       r2_r3:
        ipv4_address: "192.19.0.12"
    expose:
       - "179"

  router3:
    privileged: true
    container_name: r3
    build: ./r3
    networks:
       r2_r3:
        ipv4_address: "192.19.0.13"
       r3_r4:
        ipv4_address: "162.19.0.13"
    expose:
       - "179"

  router4:
    privileged: true
    container_name: r4
    build: ./r4
    networks:
       r3_r4:
        ipv4_address: "162.19.0.14"
    expose:
       - "179"

  router666:
    privileged: true
    container_name: r666
    build: ./r666
    networks:
       r666_r2:
        ipv4_address: "182.19.0.16"
    expose:
       - "179"
<<<<<<< Updated upstream
=======
  
  krill:
   privileged: true
   container_name: krill
   build: ./krill
   volumes:
      - /tmp/krill/data/:/var/krill/data/ #TODO this might not be needed
   networks:
        r1_r2:
         ipv4_address: "172.19.0.100"
   expose:
      - "3000"
   ports:
    - "127.0.0.1:3000:3000"
# Make routinator build only after krill 
  routinator:
   privileged: true
   user: root
   container_name: routinator
   build: ./routinator
   volumes:
      - /tmp/krill/data:/var/krill/data #TODO this might not be needed
   networks:
        r1_r2:
         ipv4_address: "172.19.0.101"
   expose:
      - "3323"
      - "9556"
   ports:
    - "127.0.0.1:3323:3323"
    - "127.0.0.1:9556:9556"
  
>>>>>>> Stashed changes

networks:
  r1_r2:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16

  r2_r3:
    driver: bridge
    ipam:
     config:
       - subnet: 192.19.0.0/16

  r3_r4:
    driver: bridge
    ipam:
     config:
       - subnet: 162.19.0.0/16

  r666_r2:
    driver: bridge
    ipam:
     config:
       - subnet: 182.19.0.0/16


